#!/usr/bin/env bash
#check if SSH agent is running, if not start it
if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval $("ssh-agent")
fi

# Add SSH private key to SSH agent
ssh-add ~/.ssh/school

# SSH into the server
ssh ubuntu@100.25.191.54

# Check SSH exit status
if [ $? -ne 0 ]; then
    echo "SSH connection failed"
    exit 1
fi
